apiVersion: v1
kind: Template
metadata:
  name: request-logger
  annotations:
    description: "Request Logger template"
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        app: ${NAME}
        deploymentconfig: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}
            deploymentconfig: ${NAME}
        spec:
          containers:
            - image: ${IMAGE_NAME}
              imagePullPolicy: IfNotPresent
              name: request-logger
              ports:
                - containerPort: 8080
                  protocol: TCP
      test: false
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${NAME}
    spec:
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: ${NAME}
        weight: 100
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}
      sessionAffinity: None
      type: ClusterIP
parameters:
  - description: The name for the deployment of the request logger
    name: NAME
    value: request-logger
  - description: The image of the request logger to take
    name: IMAGE_NAME
    value: quay.io/bakito/request-logger:latest

labels:
  app: ${NAME}
